<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1LJ39Cx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1LJ39Cx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1LJ39Cx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1LJ39Cx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1LJ39Cx\App_KernelDevDebugContainer([
    'container.build_hash' => '1LJ39Cx',
    'container.build_id' => 'a4516217',
    'container.build_time' => 1653671085,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1LJ39Cx');
